<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260804151452 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE asset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, model VARCHAR(150) DEFAULT NULL, serial_number VARCHAR(150) DEFAULT NULL, description TEXT DEFAULT NULL, purchase_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, purchase_price NUMERIC(12, 2) DEFAULT NULL, warranty_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT NOT NULL, manufacturer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2AF5A5C12469DE2 ON asset (category_id)');
        $this->addSql('CREATE INDEX IDX_2AF5A5CA23B42D ON asset (manufacturer_id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5C12469DE2 FOREIGN KEY (category_id) REFERENCES asset_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5CA23B42D FOREIGN KEY (manufacturer_id) REFERENCES manufacturer (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE asset DROP CONSTRAINT FK_2AF5A5C12469DE2');
        $this->addSql('ALTER TABLE asset DROP CONSTRAINT FK_2AF5A5CA23B42D');
        $this->addSql('DROP TABLE asset');
    }
}
